# Generated by Django 5.1.1 on 2024-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_system_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador del sistema'), (2, 'Funcionario')], default=2),
        ),
    ]
