# Generated by Django 5.1.1 on 2024-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_file', models.PositiveSmallIntegerField(choices=[(1, 'Web'), (2, 'PDF')], default=1)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('time_choices', models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scraper_url',
            },
        ),
    ]
