# Generated by Django 5.1.1 on 2024-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
