# Generated by Django 5.1.1 on 2024-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_scraperurl_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperurl',
            name='sobrenombre',
            field=models.CharField(default='prueba', max_length=120),
            preserve_default=False,
        ),
    ]
