# Generated by Django 5.1.1 on 2024-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_scraperurl_sobrenombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperurl',
            name='mode_scrapeo',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
