# Generated by Django 5.1.1 on 2024-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_scraperurl_mode_scrapeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='time_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral'), (4, '1 Hora')], default=1),
        ),
    ]
