# Generated by Django 5.1.1 on 2024-12-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_alter_scraperurl_time_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='time_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral')], default=1),
        ),
    ]
