# Generated by Django 5.1.1 on 2025-01-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_alter_scraperurl_time_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperurl',
            name='fecha_scraper',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
