# Generated by Django 5.1.1 on 2025-02-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_scraperurl_fecha_scraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='time_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral'), (4, 'Semanal')], default=1),
        ),
    ]
