# Generated by Django 5.1.1 on 2025-02-20 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_scraperurl_fecha_scraper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='time_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral'), (4, 'Semanal')], default=1),
        ),
        migrations.CreateModel(
            name='ReportComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id1', models.CharField(max_length=50)),
                ('object_id2', models.CharField(max_length=50)),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('info_agregada', models.TextField(blank=True, null=True)),
                ('info_eliminada', models.TextField(blank=True, null=True)),
                ('info_modificada', models.TextField(blank=True, null=True)),
                ('estructura_cambio', models.BooleanField(default=False)),
                ('scraper_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='shared.scraperurl')),
            ],
            options={
                'db_table': 'report_comparison',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('common_names', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('invasiveness_description', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('impact', models.JSONField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('life_cycle', models.TextField(blank=True, null=True)),
                ('reproduction', models.TextField(blank=True, null=True)),
                ('hosts', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('affected_organs', models.TextField(blank=True, null=True)),
                ('environmental_conditions', models.TextField(blank=True, null=True)),
                ('prevention_control', models.JSONField(blank=True, null=True)),
                ('uses', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('scraper_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='shared.scraperurl')),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraper_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.scraperurl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_subscription',
                'unique_together': {('user', 'scraper_url')},
            },
        ),
    ]
