# Generated by Django 5.1.1 on 2025-02-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_scraperurl_fecha_scraper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('common_names', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('invasiveness_description', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('impact', models.JSONField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('life_cycle', models.TextField(blank=True, null=True)),
                ('reproduction', models.TextField(blank=True, null=True)),
                ('hosts', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('affected_organs', models.TextField(blank=True, null=True)),
                ('environmental_conditions', models.TextField(blank=True, null=True)),
                ('prevention_control', models.JSONField(blank=True, null=True)),
                ('uses', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=500)),
                ('scraper_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='shared.scraperurl')),
            ],
        ),
    ]
