# Generated by Django 5.1.1 on 2025-02-23 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperurl',
            name='error_scrapeo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperurl',
            name='estado_scrapeo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=45),
        ),
        migrations.AddField(
            model_name='species',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scraperurl',
            name='time_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral'), (4, 'Semanal')], default=1),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='source_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
        migrations.CreateModel(
            name='ReportComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id1', models.CharField(max_length=50)),
                ('object_id2', models.CharField(max_length=50)),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('info_agregada', models.TextField(blank=True, null=True)),
                ('info_eliminada', models.TextField(blank=True, null=True)),
                ('info_modificada', models.TextField(blank=True, null=True)),
                ('estructura_cambio', models.BooleanField(default=False)),
                ('scraper_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='shared.scraperurl')),
            ],
            options={
                'db_table': 'report_comparison',
            },
        ),
        migrations.CreateModel(
            name='SpeciesSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.JSONField(blank=True, null=True)),
                ('hosts', models.JSONField(blank=True, null=True)),
                ('name_subscription', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'species_subscription',
                'unique_together': {('user', 'scientific_name', 'distribution', 'hosts')},
            },
        ),
    ]
