# Generated by Django 5.1.1 on 2025-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_alter_scraperurl_time_choices'),
        ('shared', '0010_scraperurl_error_scrapeo_scraperurl_estado_scrapeo_and_more'),
    ]

    operations = [
    ]
