# Generated by Django 5.1.1 on 2025-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_species_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperurl',
            old_name='fecha_scraper',
            new_name='ultima_fecha_scrapeo',
        ),
        migrations.AddField(
            model_name='scraperurl',
            name='error_scrapeo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperurl',
            name='estado_scrapeo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
    ]
