# Generated by Django 5.1.1 on 2025-03-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_newspecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('publication_date', models.DateField()),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='shared.newspecies')),
            ],
            options={
                'db_table': 'species_news',
                'ordering': ['-publication_date'],
            },
        ),
    ]
