# Generated by Django 5.1.1 on 2025-02-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_rename_fecha_scraper_scraperurl_ultima_fecha_scrapeo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperurl',
            old_name='ultima_fecha_scrapeo',
            new_name='fecha_scraper',
        ),
    ]
