# Generated by Django 5.1.1 on 2025-02-21 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_rename_ultima_fecha_scrapeo_scraperurl_fecha_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciessubscription',
            name='name_subscription',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speciessubscription',
            name='distribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciessubscription',
            name='hosts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
    ]
