# Generated by Django 5.1.1 on 2025-03-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_speciessubscription_name_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperurl',
            name='estado_scrapeo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=45),
        ),
    ]
