# Generated by Django 5.1.1 on 2025-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_cabispecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
