# Generated by Django 5.1.1 on 2025-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_species_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabispecies',
            name='impact',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cabispecies',
            name='prevention_control',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='impact',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='prevention_control',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
