# Generated by Django 5.1.1 on 2025-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_alter_cabispecies_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'species_news',
                'ordering': ['-publication_date'],
            },
        ),
    ]
