# Generated by Django 5.1.1 on 2025-03-17 05:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0019_speciesnews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciessubscription',
            unique_together={('user', 'scientific_name')},
        ),
        migrations.AlterField(
            model_name='speciessubscription',
            name='scientific_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='speciessubscription',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='speciessubscription',
            name='hosts',
        ),
    ]
