# Generated by Django 5.1.1 on 2025-03-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0020_alter_speciessubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciessubscription',
            name='name_subscription',
        ),
    ]
